"""Add a final-outcome loan repayment target to the feature dataset."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import pandas as pd


STATUS_DEFINITIONS = {
    "A": {
        "meaning": "finished contract, no repayment problems",
        "known_final_outcome": True,
        "repayment_default_target": 0,
        "exclusion_reason": None,
    },
    "B": {
        "meaning": "finished contract, loan not paid",
        "known_final_outcome": True,
        "repayment_default_target": 1,
        "exclusion_reason": None,
    },
    "C": {
        "meaning": "running contract, no repayment problems so far",
        "known_final_outcome": False,
        "repayment_default_target": None,
        "exclusion_reason": "running_contract_not_final",
    },
    "D": {
        "meaning": "running contract, client in debt",
        "known_final_outcome": False,
        "repayment_default_target": None,
        "exclusion_reason": "running_contract_not_final",
    },
}

TARGET_COLUMNS = [
    "loan_status_from_source",
    "loan_status_meaning",
    "repayment_outcome_known",
    "repayment_default_target",
    "target_exclusion_reason",
]


def load_loan_statuses(loans_path: Path) -> pd.DataFrame:
    if not loans_path.exists():
        raise FileNotFoundError(f"Missing loans file: {loans_path}")
    loans = pd.read_csv(loans_path, usecols=["loan_id", "status"])
    unknown = sorted(set(loans["status"]) - set(STATUS_DEFINITIONS))
    if unknown:
        raise ValueError(f"Unknown loan status values: {unknown}")
    if loans["loan_id"].duplicated().any():
        raise ValueError("Loan status source contains duplicate loan_id values")
    return loans


def build_target_columns(loans: pd.DataFrame) -> pd.DataFrame:
    target = loans.copy()
    target["loan_status_meaning"] = target["status"].map(
        lambda status: STATUS_DEFINITIONS[status]["meaning"]
    )
    target["repayment_outcome_known"] = target["status"].map(
        lambda status: STATUS_DEFINITIONS[status]["known_final_outcome"]
    )
    target["repayment_default_target"] = target["status"].map(
        lambda status: STATUS_DEFINITIONS[status]["repayment_default_target"]
    )
    target["target_exclusion_reason"] = target["status"].map(
        lambda status: STATUS_DEFINITIONS[status]["exclusion_reason"]
    )
    return target.rename(columns={"status": "loan_status_from_source"})


def target_summary(frame: pd.DataFrame) -> dict[str, Any]:
    known = frame[frame["repayment_outcome_known"]]
    excluded = frame[~frame["repayment_outcome_known"]]
    class_distribution = (
        known["repayment_default_target"]
        .astype("Int64")
        .value_counts()
        .sort_index()
        .rename(index={0: "known_good_0", 1: "known_bad_1"})
        .to_dict()
    )
    excluded_distribution = (
        excluded["loan_status_from_source"].value_counts().sort_index().to_dict()
    )
    return {
        "included_observations": int(len(known)),
        "excluded_observations": int(len(excluded)),
        "class_distribution": {str(key): int(value) for key, value in class_distribution.items()},
        "excluded_status_distribution": {
            str(key): int(value) for key, value in excluded_distribution.items()
        },
    }


def build_target_markdown(summary: dict[str, Any]) -> str:
    status_rows = "\n".join(
        (
            f"| {status} | {definition['meaning']} | "
            f"{'yes' if definition['known_final_outcome'] else 'no'} | "
            f"{definition['repayment_default_target'] if definition['repayment_default_target'] is not None else ''} |"
        )
        for status, definition in STATUS_DEFINITIONS.items()
    )
    return f"""# Loan Target Definition

Generated by `scripts/add_loan_target.py`.

## Status Meanings

| status | meaning | included in binary target | repayment_default_target |
| --- | --- | --- | --- |
{status_rows}

## Target Rationale

The binary modelling target uses only final loan outcomes. Status `A` is treated as known good (`0`) and status `B` as known bad/default (`1`). Statuses `C` and `D` are running contracts, so they are excluded from supervised target training instead of being silently treated as known defaults or known goods.

## Observation Counts

- Included observations: {summary['included_observations']}
- Excluded observations: {summary['excluded_observations']}
- Class distribution: {summary['class_distribution']}
- Excluded status distribution: {summary['excluded_status_distribution']}
"""


def add_loan_target(
    features_path: Path = Path("data/processed/nadi_features.csv"),
    loans_path: Path = Path("data/processed/pkdd/loans.csv"),
    output_path: Path = Path("data/processed/nadi_features.csv"),
    doc_path: Path = Path("docs/loan_target_definition.md"),
) -> pd.DataFrame:
    if not features_path.exists():
        raise FileNotFoundError(f"Missing feature dataset: {features_path}")

    features = pd.read_csv(features_path)
    features = features.drop(columns=[column for column in TARGET_COLUMNS if column in features.columns])
    loans = load_loan_statuses(loans_path)
    target = build_target_columns(loans)
    frame = features.merge(target, on="loan_id", how="left")

    if len(frame) != len(features):
        raise ValueError("Target merge changed feature row count")
    if frame["loan_id"].duplicated().any():
        raise ValueError("Targeted feature dataset contains duplicate loan_id values")
    if frame["loan_status_from_source"].isna().any():
        raise ValueError("Some feature rows did not receive a loan target status")
    if (frame["repayment_outcome_known"] & frame["repayment_default_target"].isna()).any():
        raise ValueError("Known outcome rows must have a binary target")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output_path, index=False, encoding="utf-8")

    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(build_target_markdown(target_summary(frame)), encoding="utf-8")
    return frame


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--features-path", type=Path, default=Path("data/processed/nadi_features.csv"))
    parser.add_argument("--loans-path", type=Path, default=Path("data/processed/pkdd/loans.csv"))
    parser.add_argument("--output-path", type=Path, default=Path("data/processed/nadi_features.csv"))
    parser.add_argument("--doc-path", type=Path, default=Path("docs/loan_target_definition.md"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    frame = add_loan_target(args.features_path, args.loans_path, args.output_path, args.doc_path)
    summary = target_summary(frame)
    print(f"Wrote targeted features to {args.output_path} with {len(frame)} rows.")
    print(f"Wrote target definition to {args.doc_path}.")
    print(f"Included observations: {summary['included_observations']}")
    print(f"Excluded observations: {summary['excluded_observations']}")
    print(f"Class distribution: {summary['class_distribution']}")


if __name__ == "__main__":
    main()
