"""Evaluate decision-policy behavior over the generated NADI feature dataset."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


def pct(series: pd.Series) -> dict[str, float]:
    if series.empty:
        return {}
    return {str(key): round(float(value) * 100, 2) for key, value in series.value_counts(normalize=True, dropna=False).items()}


def risk_band(probability: Any) -> str:
    value = float(probability) if not pd.isna(probability) else 0.5
    if value <= 0.2:
        return "low"
    if value <= 0.5:
        return "medium"
    return "high"


def amount_delta(row: pd.Series) -> float:
    requested = float(row.get("requested_amount") or 0)
    recommended = float(row.get("decision_recommended_amount") or row.get("recommended_amount") or 0)
    return recommended - requested


def confusion(frame: pd.DataFrame) -> dict[str, int]:
    if "repayment_default_target" not in frame or "repayment_outcome_known" not in frame:
        return {}
    known = frame[frame["repayment_outcome_known"] == True].copy()
    if known.empty:
        return {}
    predicted_positive = known["decision_state"].isin(["APPROVE", "SAFE_TO_LEARN"])
    defaulted = known["repayment_default_target"].astype(int) == 1
    return {
        "approved_or_starter_and_repaid": int((predicted_positive & ~defaulted).sum()),
        "approved_or_starter_and_defaulted": int((predicted_positive & defaulted).sum()),
        "declined_or_evidence_needed_and_repaid": int((~predicted_positive & ~defaulted).sum()),
        "declined_or_evidence_needed_and_defaulted": int((~predicted_positive & defaulted).sum()),
    }


def build_report(frame: pd.DataFrame) -> str:
    frame = frame.copy()
    frame["risk_band"] = frame["risk_model_probability"].map(risk_band) if "risk_model_probability" in frame else "unknown"
    frame["amount_delta"] = frame.apply(amount_delta, axis=1)
    safe_share = float((frame.get("maximum_safe_exposure", pd.Series(dtype=float)).fillna(0) > 0).mean()) if len(frame) else 0.0
    stress = frame.get("stress_probability", pd.Series(dtype=float))
    sensitivity = []
    if "risk_model_probability" in frame:
        for shift in [-0.1, -0.05, 0.05, 0.1]:
            shifted = (frame["risk_model_probability"].fillna(0.5) + shift).clip(0, 1)
            sensitivity.append({"risk_shift": shift, "low_or_medium_share_pct": round(float((shifted <= 0.5).mean()) * 100, 2)})
    metrics = {
        "rows": int(len(frame)),
        "decision_distribution_pct": pct(frame["decision_state"]) if "decision_state" in frame else {},
        "risk_band_distribution_pct": pct(frame["risk_band"]),
        "confidence_distribution_pct": pct(frame["confidence_band"]) if "confidence_band" in frame else {},
        "stress_distribution": {
            "mean": round(float(stress.mean()), 4) if not stress.empty else None,
            "p90": round(float(stress.quantile(0.9)), 4) if not stress.empty else None,
        },
        "repayment_envelope": {
            "safe_exposure_available_share_pct": round(safe_share * 100, 2),
            "median_maximum_safe_exposure": round(float(frame.get("maximum_safe_exposure", pd.Series(dtype=float)).fillna(0).median()), 2),
        },
        "requested_vs_recommended": {
            "median_delta": round(float(frame["amount_delta"].median()), 2) if len(frame) else 0,
            "recommended_below_requested_share_pct": round(float((frame["amount_delta"] < 0).mean()) * 100, 2) if len(frame) else 0,
        },
        "label_analysis": confusion(frame),
        "sensitivity_analysis": sensitivity,
    }
    return "# Policy Evaluation\n\nGenerated by `scripts/evaluate_policies.py`.\n\n```json\n" + json.dumps(metrics, indent=2) + "\n```\n\nPolicy values remain configurable in `backend/app/core/*.json`.\n"


def evaluate_policies(features_path: Path = Path("data/processed/nadi_features.csv"), output_path: Path = Path("docs/policy_evaluation.md")) -> str:
    if not features_path.exists():
        raise FileNotFoundError(f"Missing feature dataset: {features_path}")
    report = build_report(pd.read_csv(features_path))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--features-path", type=Path, default=Path("data/processed/nadi_features.csv"))
    parser.add_argument("--output-path", type=Path, default=Path("docs/policy_evaluation.md"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    evaluate_policies(args.features_path, args.output_path)
    print(f"Wrote policy evaluation report to {args.output_path}.")


if __name__ == "__main__":
    main()

